[package]
name = "snocat-cli"
description = "Streaming Network Overlay Connection Arbitration Tunnel"
version = "0.2.0-alpha.10"
authors = ["Microsoft Corporation", "Zoey <Dessix@Dessix.net>"]
edition = "2018"
license = "MIT OR Apache-2.0"
repository = "https://github.com/microsoft/snocat"
categories = ["network-programming", "command-line-utilities"]
include = ["src/**/*", "build.rs", "Cargo.toml", "LICENSE*", "*.md"]

[dependencies]
snocat = { version= "^0.2.0-alpha.13"}
anyhow = "~1.0.42"
downcast-rs = "^1.2.0"
clap = "~2.33.3"
futures = "^0.3.15"
futures-io = "^0.3.15"
gen-z = "~0.1.0"
log = "~0.4.13"
quinn = "~0.7.2"
rcgen = "0.8"
thiserror = { version = "^1.0.26", git = "https://github.com/Dessix/thiserror", rev = "e863837edfee78d894647fc415a2e7760512eb6a" }
tracing = "~0.1.22"
tracing-futures = "~0.2.4"
tracing-subscriber = "~0.2.19"
tokio = { version="^1.8.1", features=["net", "io-util", "signal", "macros"] }
tokio-stream = { version="^0.1.7", features=["net", "io-util"] }
tokio-util = { version="^0.6.7", features=[] }
